apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: otit
spec:
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: otit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: postgresuser
        - name: POSTGRES_PASSWORD
          value: secretPassword1234
        - name: POSTGRES_DB
          value: otit
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        image: postgres:14.5
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
      affinity:
        podAntiAffinity: #https://medium.com/@johnjjung/building-a-kubernetes-daemonstatefulset-30ad0592d8cb
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - dremio
                      - postgresql
                      - ontop
              topologyKey: "kubernetes.io/hostname"