apiVersion: v1
kind: Service
metadata:
  labels:
    app: ontop
  name: ontop
  namespace: chrontext
spec:
  clusterIP: None
  selector:
    app: ontop
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ontop
  namespace: chrontext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ontop
  serviceName: ontop
  template:
    metadata:
      labels:
        app: ontop
    spec:
      containers:
        - env:
          - name: ONTOP_MAPPING_FILE
            value: /opt/ontop/input/mapping.obda
          - name: ONTOP_DB_USER
            value: mba
          - name: ONTOP_DB_PASSWORD
            value: Qi3CQzuqK5DTJcS
          - name: ONTOP_DB_DRIVER
            value: com.dremio.jdbc.Driver
          - name: ONTOP_DB_URL
            value: jdbc:dremio:direct=dremio-client.default.svc.cluster.local:31010
          image: iiiiiiiiiii.dkr.ecr.eu-west-2.amazonaws.com/ontop:latest
          imagePullPolicy: Always
          name: ontop
          ports:
          - containerPort: 8080
          - containerPort: 8082
      affinity:
        podAntiAffinity: #https://medium.com/@johnjjung/building-a-kubernetes-daemonstatefulset-30ad0592d8cb
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - postgresql
                      - ontop
                      - dremio
              topologyKey: "kubernetes.io/hostname"